# Generated by Django 4.2.23 on 2025-06-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('contact_number', models.CharField(max_length=15)),
                ('favorite_foods', models.CharField(max_length=100)),
                ('movies_rating', models.IntegerField()),
                ('radio_rating', models.IntegerField()),
                ('eat_out_rating', models.IntegerField()),
                ('tv_rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
